version: "3.9"
services:
  db:
    image: mysql:8.4.0-oraclelinux8
    container_name: "gnarly.db"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "gnarly"
      MYSQL_USER: "gnarly"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
